# Generated by Django 5.2.8 on 2025-12-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsnapshot',
            name='price',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketsnapshot',
            name='volume_24h',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=30),
            preserve_default=False,
        ),
    ]
